### PR TITLE
Feature/refactor

### PR DESCRIPTION
**Pull request by AlaaMYahya**
Used useExpressServer instead of createExpressServer, added Eslint and Prettier

### CODE REVIEW

**Review by kamelth — CHANGES_REQUESTED** [review]
Please first I need you to use `.gitignore` file so that `node_modules` folder and all js files are not included in the repo.

**Comment by AlaaMYahya** [comment]
I did that and pushed it again, but I think the `node_modules` and all the js files were not deleted, just the `.gitignore` file added.

**Comment by kamelth** [comment]
> I did that and pushed it again, but I think the `node_modules` and all the js files were not deleted, just the `.gitignore` file added.

1. Make sure there's a slash after node_modules to indicate it's a directory like this: `node_modules/`
2. It's possible that the files you're trying to ignore were already tracked by Git before you added the .gitignore file. In that case, you need to untrack them with:
```bash
git rm --cached node_modules
git rm --cached *.js
```

**Review by kamelth — CHANGES_REQUESTED** [review]
I will approve this PR after you resolve these conflicts:
index.ts
src/app.ts
src/config/data-source.ts
src/controllers/user.controller.ts
src/services/user.service.ts
tsconfig.json

**Comment by AlaaMYahya** [comment]
> 2\. to untrack

Thank you.
Done
And I used to untrack  node_modules with following command
`git rm -r --cached node_modules`

**Pull request merged**
